# Generated by Django 5.2.17 on 2026-10-01 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_domain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hiringrequest',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hiringrequest',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hiringrequest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hiringrequest',
            name='employment_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='hiringrequest',
            name='location',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='hiringrequest',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidateattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hiringrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Bản nháp'), ('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('closed', 'Đã đóng')], default='draft', max_length=16),
        ),
    ]
