# Generated by Django 5.2.17 on 2026-10-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_domain', '0002_application_consent_at_application_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interviewer_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='application',
            name='recruiter_note',
            field=models.TextField(blank=True),
        ),
    ]
