# Generated by Django 5.2.17 on 2026-10-03 09:59

from django.db import migrations, models


def collapse_offer(apps, schema_editor):
    Application = apps.get_model('recruitment_domain', 'Application')
    Application.objects.using(schema_editor.connection.alias).filter(stage='offer').update(
        stage='interview', version=models.F('version') + 1,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_domain', '0003_application_interview_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringrequest',
            name='utilization_plan',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(collapse_offer, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('new', 'Mới'), ('screening', 'Sàng lọc'), ('interview', 'Phỏng vấn'), ('hired', 'Đã tuyển'), ('rejected', 'Từ chối')], default='new', max_length=16),
        ),
        migrations.AlterField(
            model_name='applicationtransition',
            name='from_stage',
            field=models.CharField(choices=[('new', 'Mới'), ('screening', 'Sàng lọc'), ('interview', 'Phỏng vấn'), ('hired', 'Đã tuyển'), ('rejected', 'Từ chối'), ('offer', 'Đề nghị (trước đây)')], max_length=16),
        ),
        migrations.AlterField(
            model_name='applicationtransition',
            name='to_stage',
            field=models.CharField(choices=[('new', 'Mới'), ('screening', 'Sàng lọc'), ('interview', 'Phỏng vấn'), ('hired', 'Đã tuyển'), ('rejected', 'Từ chối'), ('offer', 'Đề nghị (trước đây)')], max_length=16),
        ),
    ]
