import {useEffect,useRef,useState} from 'react'
import type {MouseEvent} from 'react'
import type {Session} from '../types'
import {SettingsMenu,type Theme} from '../components/SettingsMenu'
import {AppIcon} from '../components/AppIcon'
import {demoOrders,demoSources,demoDeliveryStates,money,date,type DemoOrder} from './demoOrders'
import './crm-app.css'

const sections=[
 {slug:'orders',title:'Quản lý đơn hàng',description:'Một đơn có thể có nhiều bản ghi nguồn. Xem đơn trước, kiểm tra dữ liệu sau.'},
 {slug:'ads',title:'Chi phí & hiệu quả quảng cáo',description:'Phác thảo dữ liệu cần có để nối chi phí quảng cáo với kết quả bán hàng.'},
 {slug:'reports',title:'Thống kê',description:'Báo cáo tính từ cùng tập đơn đã lọc; chưa phải doanh thu kế toán.'},
 {slug:'accounting',title:'Kế toán',description:'Phác thảo đối soát tiền và chi phí với đơn vị kho vận bên thứ ba.'},
 {slug:'review',title:'Nội dung cần duyệt',description:'Trao đổi với Leader, người xử lý đơn và kế toán trước khi kết nối dữ liệu thật.'},
]
const defaults={search:'',from:'2026-10-01',to:'2026-10-30',source:'',status:''}
const contract='THESIS: Independent MRECRM site, one order and several source records. OWN-WORLD: Carbon header, yellow selection, white ledger. STORY: Inspect synthetic orders and consistent reports before defining operations. FIRST VIEWPORT: CRM header and navigation, filters, ledger and right panel. FORM: Approved table/side-panel composition. FINISH: unreviewed and undocumented is unfinished; this build ends with the finish review, the verdict, DESIGN.md, and every shipping raster carrying its provenance'
function Badge({text}:{text:string}){return <span className={`badge ${text==='Giao thành công'?'good':['Hoàn hàng','Đã hủy'].includes(text)?'bad':text==='Đang giao'?'warning':''}`}>{text}</span>}

export function CRMApp({session,theme,onThemeChange,onLogout}:{session:Session;theme:Theme;onThemeChange:(theme:Theme)=>void;onLogout:()=>void}){
 const [path,setPath]=useState(window.location.pathname),[filters,setFilters]=useState(defaults),[page,setPage]=useState(1),[selected,setSelected]=useState<DemoOrder|null>(null)
 const [mobile,setMobile]=useState(()=>window.matchMedia('(max-width:700px)').matches)
 const rootRef=useRef<HTMLDivElement>(null),mainRef=useRef<HTMLElement>(null),closeRef=useRef<HTMLButtonElement>(null),panelRef=useRef<HTMLElement>(null),openerId=useRef<string|null>(null)
 const section=sections.find(s=>path===`/crm/${s.slug}`)
 const rows=demoOrders.filter(o=>(!filters.search||`${o.id} ${o.name} ${o.product}`.toLocaleLowerCase('vi').includes(filters.search.trim().toLocaleLowerCase('vi')))&&(!filters.from||o.date>=filters.from)&&(!filters.to||o.date<=filters.to)&&(!filters.source||o.sources.includes(filters.source))&&(!filters.status||o.delivery===filters.status))
 const count=rows.length,value=rows.reduce((s,o)=>s+o.value,0),records=rows.reduce((s,o)=>s+o.sources.length,0),pages=Math.max(1,Math.ceil(count/12)),currentPage=Math.min(page,pages)
 useEffect(()=>{
  const comment=document.createComment(contract);rootRef.current?.prepend(comment)
  const oldTitle=document.title,media=window.matchMedia('(max-width:700px)'),resize=()=>setMobile(media.matches),pop=()=>{setPath(window.location.pathname);setSelected(null)}
  media.addEventListener('change',resize);window.addEventListener('popstate',pop)
  return ()=>{comment.remove();document.title=oldTitle;media.removeEventListener('change',resize);window.removeEventListener('popstate',pop)}
 },[])
 useEffect(()=>{if(path==='/crm'||path==='/crm/'){window.history.replaceState(null,'','/crm/orders');setPath('/crm/orders')}},[path])
 useEffect(()=>{document.title=`${section?.title??'Không tìm thấy trang'} · MRECRM`},[section])
 useEffect(()=>{if(selected){panelRef.current?.scrollTo(0,0);closeRef.current?.focus()}},[selected])
 function closeDetail(){setSelected(null);requestAnimationFrame(()=>{(document.getElementById(`crm-open-${openerId.current}`)??mainRef.current)?.focus()})}
 useEffect(()=>{
  if(!selected)return
  const keys=(e:KeyboardEvent)=>{if(e.key==='Escape')closeDetail();if(mobile&&e.key==='Tab'){e.preventDefault();closeRef.current?.focus()}}
  document.addEventListener('keydown',keys);return ()=>document.removeEventListener('keydown',keys)
 },[selected,mobile])
 function navigate(e:MouseEvent<HTMLAnchorElement>,slug:string){if(e.button!==0||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();window.history.pushState(null,'',`/crm/${slug}`);setPath(`/crm/${slug}`);setSelected(null);requestAnimationFrame(()=>mainRef.current?.focus())}
 function filter(key:keyof typeof filters,val:string){setFilters(f=>({...f,[key]:val}));setPage(1);setSelected(null)}
 function reset(){setFilters(defaults);setPage(1);setSelected(null)}
 function openOrder(o:DemoOrder){openerId.current=o.id;setSelected(o)}
 return <div ref={rootRef} className={`crm-app ${selected?'crm-detail-open':''}`}>
  <div className="crm-frame" inert={mobile&&!!selected}>
   <header className="product-bar"><a className="brand" href="/crm/orders" onClick={e=>navigate(e,'orders')} aria-label="MRECRM — Quản lý đơn hàng"><img src="/brand/mr-ecom-logo.png" alt=""/><strong>MRECRM</strong></a><a className="erp-return" href="/">Về MRERP <AppIcon name="external" size={14}/></a><div className="crm-account"><span className="crm-user">{session.display_name}<small>{session.employee_code}</small></span><SettingsMenu theme={theme} onThemeChange={onThemeChange} onOpenSettings={()=>window.location.assign('/?workspace=settings')} onLogout={onLogout}/></div></header>
   <div className="demo-notice"><strong>Dữ liệu minh họa</strong><span>60 đơn giả · 72 bản ghi nguồn · Chưa kết nối Webcake, POS hoặc Google Sheet.</span></div>
   <div className="shell"><aside className="sidebar"><nav aria-label="Chức năng CRM">{sections.map(s=><a key={s.slug} href={`/crm/${s.slug}`} className={section===s?'selected':''} aria-current={section===s?'page':undefined} onClick={e=>navigate(e,s.slug)}>{s.slug==='ads'?'Quảng cáo':s.title}</a>)}</nav><p>Trạng thái, trường dữ liệu và cách đối chiếu hiện là đề xuất.</p></aside>
   <main id="crm-main" ref={mainRef} tabIndex={-1}>
    <header className="page-heading"><div><h1>{section?.title??'Không tìm thấy trang CRM'}</h1><p>{section?.description??'Chọn một mục trong menu để tiếp tục.'}</p></div><a className="review-link" href="/crm/review" onClick={e=>navigate(e,'review')}>Góp ý với Leader <AppIcon name="external" size={14}/></a></header>
    {['orders','reports'].includes(section?.slug??'')&&<section className="filters" aria-label="Lọc đơn minh họa"><label className="search">Tìm đơn<input type="search" placeholder="Mã đơn, tên khách, sản phẩm…" value={filters.search} onChange={e=>filter('search',e.target.value)}/></label><label>Từ ngày<input type="date" value={filters.from} onChange={e=>filter('from',e.target.value)}/></label><label>Đến ngày<input type="date" value={filters.to} onChange={e=>filter('to',e.target.value)}/></label><label>Nguồn dữ liệu<select aria-label="Nguồn dữ liệu" value={filters.source} onChange={e=>filter('source',e.target.value)}><option value="">Tất cả nguồn</option>{demoSources.map(s=><option key={s}>{s}</option>)}</select></label><label>Giao hàng<select aria-label="Giao hàng" value={filters.status} onChange={e=>filter('status',e.target.value)}><option value="">Tất cả trạng thái</option>{demoDeliveryStates.map(s=><option key={s}>{s}</option>)}</select></label><button className="quiet" onClick={reset}>Đặt lại</button></section>}
    {section?.slug==='orders'&&<><div className="ledger-summary"><div><strong>{count} đơn</strong> <span className="muted">/ {records} bản ghi nguồn</span></div><div>Giá trị đơn <strong>{money(value)}</strong></div></div>{count?<><div className="table-wrap"><table><caption className="sr-only">Danh sách đơn minh họa</caption><thead><tr><th>Mã đơn / Ngày</th><th>Khách hàng</th><th>Sản phẩm</th><th className="number">Giá trị</th><th>Nguồn dữ liệu</th><th>Giao hàng</th></tr></thead><tbody>{rows.slice((currentPage-1)*12,currentPage*12).map(o=><tr key={o.id} className={selected?.id===o.id?'chosen':''} onClick={()=>openOrder(o)}><td><button id={`crm-open-${o.id}`} className="order-link" aria-label={`Xem chi tiết ${o.id}`} onClick={e=>{e.stopPropagation();openOrder(o)}}>{o.id}</button><small>{date(o.date)}</small></td><td>{o.name}<small>{o.phone}</small></td><td>{o.product}<small>Số lượng: {o.quantity}</small></td><td className="number">{money(o.value)}</td><td className="sources">{o.origin}{o.sources.length>1&&<em>+1 nguồn</em>}</td><td><Badge text={o.delivery}/></td></tr>)}</tbody></table></div><div className="pagination"><span>{(currentPage-1)*12+1}–{Math.min(currentPage*12,count)} / {count} đơn</span><div><button disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>Trước</button><span>Trang {currentPage} / {pages}</span><button disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}>Sau</button></div></div></>:<Empty reset={reset}/>}<p className="source-note"><strong>Đếm một lần cho mỗi đơn minh họa.</strong> 12 đơn có bản ghi ở hai nguồn. Liên kết cùng một đơn được khai báo trong dữ liệu giả; quy tắc đối chiếu dữ liệu thật chưa được chốt. Lọc nguồn chọn đơn có mặt ở nguồn đó.</p></>}
    {section?.slug==='reports'&&<Reports rows={rows} reset={reset}/>}
    {['ads','accounting'].includes(section?.slug??'')&&<Prerequisites ads={section?.slug==='ads'}/>}
    {section?.slug==='review'&&<ReviewQuestions/>}
    {!section&&<div className="empty"><h2>Trang này chưa có trong CRM</h2><a href="/crm/orders" onClick={e=>navigate(e,'orders')}>Trở về đơn hàng</a></div>}
    <div className="sr-only" aria-live="polite">{section?.title}. {count} đơn trong bộ lọc.</div>
   </main></div>
  </div>
  {selected&&<aside ref={panelRef} className="detail" aria-labelledby="crm-detail-title"><div className="detail-heading"><div><h2 id="crm-detail-title">{selected.id}</h2><p className="intro">{date(selected.date)} · Đơn minh họa</p></div><button ref={closeRef} className="close" aria-label="Đóng chi tiết đơn" onClick={closeDetail}>Đóng <AppIcon name="close" size={14}/></button></div>
   <dl className="facts"><div><dt>Khách hàng</dt><dd>{selected.name}</dd></div><div><dt>Điện thoại</dt><dd>{selected.phone}</dd></div><div><dt>Địa chỉ</dt><dd>{selected.address}</dd></div><div><dt>Nguồn bản ghi đầu tiên</dt><dd>{selected.origin}</dd></div></dl>
   <h3>Sản phẩm & giá trị đơn</h3><div className="table-wrap"><table><thead><tr><th>Sản phẩm</th><th className="number">SL</th><th className="number">Thành tiền</th></tr></thead><tbody><tr><td>{selected.product}<small>{money(selected.price)} / sản phẩm</small></td><td className="number">{selected.quantity}</td><td className="number">{money(selected.value)}</td></tr></tbody></table></div>
   <div className="status-list">{[['Xử lý đơn',selected.processing],['Giao hàng',selected.delivery],['Thanh toán',selected.payment]].map(([label,status])=><div key={label}><span>{label}</span><Badge text={status}/></div>)}</div>
   <h3>Bản ghi nguồn ({selected.sources.length})</h3>{selected.sources.map((s,i)=><div key={s} className="source-evidence"><strong>{s}</strong><span>Mã giả: {s==='Webcake'?'WC':s==='POS'?'POS':'SHEET'}-{selected.id.slice(-4)}{i?' · Bản ghi bổ sung':''}</span></div>)}<p className="intro">{selected.sources.length>1?'Hai bản ghi đã gắn vào cùng một đơn minh họa. Không cộng thêm một đơn vào báo cáo.':'Đơn này có một bản ghi nguồn trong dữ liệu minh họa.'}</p>
   <h2>Lịch sử minh họa</h2><ol className="timeline"><li>Tạo bản ghi từ {selected.origin}<small>{date(selected.date)} · 09:00</small></li>{selected.sources.length>1&&<li>Có thêm bản ghi từ {selected.sources[1]}<small>{date(selected.date)} · 09:15 · Liên kết được khai báo sẵn</small></li>}<li>Trạng thái hiện tại: {selected.delivery}<small>Ví dụ để duyệt cách hiển thị; chưa mô tả quy trình thực tế.</small></li></ol><div className="detail-foot">Chỉ xem minh họa. Chưa có thao tác xác nhận đơn, chuyển kho, sửa trạng thái hay lưu dữ liệu.</div>
  </aside>}
 </div>
}
function Empty({reset}:{reset:()=>void}){return <div className="empty"><h2>Không có đơn phù hợp</h2><p>Thử đổi từ khóa, thời gian hoặc trạng thái.</p><button onClick={reset}>Đặt lại bộ lọc</button></div>}
function group(rows:DemoOrder[],key:'origin'|'product'|'date'){
 const map=new Map<string,{name:string;count:number;value:number;delivered:number}>()
 for(const o of rows){const name=o[key],g=map.get(name)??{name,count:0,value:0,delivered:0};g.count++;g.value+=o.value;if(o.delivery==='Giao thành công')g.delivered++;map.set(name,g)}
 return [...map.values()]
}
function GroupTable({rows,label,field}:{rows:DemoOrder[];label:string;field:'origin'|'product'}){return <div><h2>{label}</h2><div className="table-wrap"><table><thead><tr><th>{field==='origin'?'Nguồn đầu tiên':'Sản phẩm'}</th><th className="number">Đơn</th><th className="number">Giá trị</th><th className="number">Đã giao</th></tr></thead><tbody>{group(rows,field).map(g=><tr key={g.name}><td>{g.name}</td><td className="number">{g.count}</td><td className="number">{money(g.value)}</td><td className="number">{g.delivered}</td></tr>)}</tbody></table></div></div>}
function Reports({rows,reset}:{rows:DemoOrder[];reset:()=>void}){
 const n=rows.length,value=rows.reduce((s,o)=>s+o.value,0),delivered=rows.filter(o=>o.delivery==='Giao thành công'),returned=rows.filter(o=>o.delivery==='Hoàn hàng').length,cancelled=rows.filter(o=>o.delivery==='Đã hủy').length,pct=(x:number)=>n?`${(x/n*100).toFixed(1).replace('.',',')}%`:'—'
 const metrics=[['Số đơn',String(n),'Mỗi đơn minh họa đếm một lần'],['Giá trị đơn',money(value),'Tổng giá trị sản phẩm trong đơn'],['Giá trị đã giao',money(delivered.reduce((s,o)=>s+o.value,0)),'Chưa đồng nghĩa tiền đã nhận'],['Trung bình mỗi đơn',n?money(value/n):'—','Giá trị đơn / số đơn'],['Giao thành công',pct(delivered.length),`${delivered.length} / ${n} đơn`],['Hoàn hàng',pct(returned),`${returned} / ${n} đơn`],['Hủy đơn',pct(cancelled),`${cancelled} / ${n} đơn`],['Bản ghi nguồn',String(rows.reduce((s,o)=>s+o.sources.length,0)),'Không dùng làm số đơn']]
 const days=group(rows,'date'),max=Math.max(1,...days.map(d=>d.count))
 return <><p className="muted">{n} đơn trong bộ lọc hiện tại. Trạng thái là snapshot minh họa.</p><dl className="metrics">{metrics.map(([label,val,note])=><div className="metric" key={label}><dt>{label}</dt><dd>{val}<small>{note}</small></dd></div>)}</dl>{n?<><div className="report-grid"><GroupTable rows={rows} label="Theo nguồn dữ liệu" field="origin"/><GroupTable rows={rows} label="Theo sản phẩm" field="product"/></div><h2>Số đơn theo ngày</h2><div className="bars">{days.map(d=><div className="bar-row" key={d.name}><span>{date(d.name)}</span><div className="bar-track"><span style={{width:`${d.count/max*100}%`}}/></div><strong className="number">{d.count}</strong></div>)}</div></>:<Empty reset={reset}/>}<details className="definitions"><summary>Cách tính & cách tránh đếm trùng trong bản mẫu</summary><p>Mỗi đơn nhóm theo nguồn bản ghi đầu tiên; đây là quy ước demo, chưa phải nguồn chuẩn được duyệt. Tỷ lệ giao / hoàn / hủy lấy toàn bộ số đơn đã lọc làm mẫu số. Khi không có đơn, tỷ lệ và trung bình là “—”. Giá trị đơn không gồm phí vận chuyển, giảm giá hay hoàn tiền.</p></details><h2>Chỉ số cần thêm dữ liệu</h2><div className="table-wrap"><table><thead><tr><th>Chỉ số</th><th>Dữ liệu còn thiếu</th><th>Trạng thái</th></tr></thead><tbody>{[['ROAS','Chi phí quảng cáo, quy tắc gắn đơn với chiến dịch và cơ sở doanh thu'],['Chi phí mỗi đơn','Chi phí quảng cáo cùng kỳ, cách phân bổ và tập đơn được tính'],['Lợi nhuận','Giá vốn, phí kho vận, quảng cáo, hoàn hàng và chi phí khác'],['COD chưa nhận','Tiền thu hộ dự kiến, bảng chuyển tiền và kết quả đối soát']].map(([label,missing])=><tr key={label}><td>{label}</td><td>{missing}</td><td><Badge text="Cần thêm dữ liệu"/></td></tr>)}</tbody></table></div></>
}
function Prerequisites({ads}:{ads:boolean}){return <section className="requirements"><h2>{ads?'Nối chi phí với kết quả bán hàng':'Biết khoản nào đã nhận, khoản nào còn chênh lệch'}</h2><p>{ads?'Cần cách ghi nhận chi phí và quy tắc gắn đơn với quảng cáo trước khi tính hiệu quả.':'Cần bảng đối soát kho vận bên thứ ba và quy tắc kế toán được duyệt để đối chiếu với đơn.'}</p><h3>Dữ liệu cần chuẩn bị</h3><ul>{(ads?['Chi phí theo ngày, tài khoản và chiến dịch quảng cáo.','Mã liên kết chiến dịch / nguồn bán với đơn; cách xử lý đơn chưa xác định nguồn.','Cơ sở doanh thu: giá trị tạo đơn, giao thành công hay tiền thực nhận.','Quyền xem chi phí và hiệu quả theo nhân sự / Team.']:['Bảng thu hộ COD, mã vận đơn và kỳ chuyển tiền.','Phí giao hàng, lưu kho, hoàn hàng và các khoản khấu trừ.','Giá vốn, giảm giá, hoàn tiền và chứng từ liên quan.','Ai đối soát, ai duyệt chênh lệch và thời điểm khóa kỳ.']).map(t=><li key={t}>{t}</li>)}</ul><Badge text="Chưa kết nối · Chưa có nghiệp vụ"/></section>}
const reviewQuestions=[
 {title:'Quy trình xử lý đơn thực tế',description:'Nhờ một người đang xử lý đơn mô tả từ lúc phát sinh đến giao thành công hoặc hoàn/hủy.',questions:['Ai xác nhận đơn? Ai chuyển cho kho bên thứ ba?','Nhân sự thao tác ở Webcake, POS hay Sheet trong từng bước?','Khi giao thất bại, hoàn hàng hoặc sửa đơn, dữ liệu được cập nhật ở đâu?']},
 {title:'Nguồn chuẩn & đơn xuất hiện nhiều nơi',description:'Chưa chốt cách nhận ra cùng một đơn bằng dữ liệu thật.',questions:['Ba nguồn có dùng chung mã đơn không?','Nếu giá trị hoặc trạng thái khác nhau, lấy dữ liệu từ đâu?','Ai kiểm tra trường hợp chưa rõ hoặc nghi trùng?']},
 {title:'Quyền xem & thao tác',description:'Chưa suy ra quyền CRM từ quyền MRERP hiện có.',questions:['Ads, người xử lý đơn, Leader và kế toán được xem trường nào?','Ai được sửa đơn, xem thông tin khách, xem chi phí và xuất dữ liệu?','Phạm vi quyền theo Team, nhân sự, shop hay toàn công ty?']},
]
function ReviewQuestions(){return <div className="review-sheet">{reviewQuestions.map(q=><section key={q.title}><h2>{q.title}</h2><p>{q.description}</p><ul>{q.questions.map(t=><li key={t}>{t}</li>)}</ul></section>)}<section><h2>Sau buổi duyệt</h2><p>Chuẩn bị mẫu đã ẩn thông tin khách từ cả ba nguồn, bảng kho vận / COD và bảng chi phí quảng cáo. Chốt định nghĩa chỉ số trước khi làm nhập dữ liệu và báo cáo thật.</p></section></div>}
