# Generated by Django 5.2.17 on 2026-08-29 05:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people_domain', '0005_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('feed', 'Bảng tin'), ('task', 'Công việc'), ('goal', 'Mục tiêu'), ('leave', 'Nghỉ phép'), ('account', 'Tài khoản')], max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('target_type', models.CharField(max_length=40)),
                ('target_uuid', models.UUIDField(blank=True, null=True)),
                ('deduplication_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='people_domain.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='dashboard_d_recipie_9f023b_idx')],
            },
        ),
    ]
