# Generated by Django 5.2.17 on 2026-10-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_domain', '0002_phase_3_notification_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('feed', 'Bảng tin'), ('task', 'Công việc'), ('goal', 'Mục tiêu'), ('leave', 'Nghỉ phép'), ('account', 'Tài khoản'), ('recruitment', 'Tuyển dụng'), ('performance', 'Đánh giá nhân sự'), ('document', 'Tài liệu'), ('recognition', 'Ghi nhận')], max_length=16),
        ),
    ]
