# Generated by Django 5.2.17 on 2026-08-29 07:45

import django.db.models.deletion
import uuid
from datetime import date
from django.conf import settings
from django.db import migrations, models


HOLIDAY_SOURCE = "Lịch nghỉ Việt Nam 2026 · Chính phủ/Bộ Nội vụ"


def seed_vietnam_holidays_2026(apps, schema_editor):
    PublicHoliday = apps.get_model('leave_domain', 'PublicHoliday')
    holidays = [
        (date(2026, 1, 1), "Tết Dương lịch"),
        (date(2026, 2, 16), "Tết Âm lịch"),
        (date(2026, 2, 17), "Tết Âm lịch"),
        (date(2026, 2, 18), "Tết Âm lịch"),
        (date(2026, 2, 19), "Tết Âm lịch"),
        (date(2026, 2, 20), "Tết Âm lịch"),
        (date(2026, 4, 27), "Nghỉ bù Giỗ Tổ Hùng Vương"),
        (date(2026, 4, 30), "Ngày Chiến thắng"),
        (date(2026, 5, 1), "Ngày Quốc tế Lao động"),
        (date(2026, 9, 1), "Nghỉ liền kề Quốc khánh"),
        (date(2026, 9, 2), "Quốc khánh"),
        (date(2026, 11, 24), "Ngày Văn hóa Việt Nam"),
    ]
    for holiday_date, name in holidays:
        PublicHoliday.objects.get_or_create(
            date=holiday_date,
            defaults={"name": name, "source": HOLIDAY_SOURCE, "is_active": True},
        )


def unseed_vietnam_holidays_2026(apps, schema_editor):
    PublicHoliday = apps.get_model('leave_domain', 'PublicHoliday')
    PublicHoliday.objects.filter(source=HOLIDAY_SOURCE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('leave_domain', '0001_initial'),
        ('people_domain', '0005_alter_employee_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('source', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceAdjustment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='Luôn là ngày đầu tháng.')),
                ('days', models.SmallIntegerField(default=0)),
                ('reason', models.CharField(max_length=500)),
                ('adjusted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_adjustments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_adjustments', to='people_domain.employee')),
            ],
            options={
                'ordering': ['-month', 'employee__employee_code'],
                'permissions': [('adjust_company_attendance', 'Can adjust company attendance projection')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'month'), name='unique_attendance_adjustment_per_month'), models.CheckConstraint(condition=models.Q(('days__gte', -31), ('days__lte', 31)), name='attendance_adjustment_days_range')],
            },
        ),
        migrations.RunPython(seed_vietnam_holidays_2026, unseed_vietnam_holidays_2026),
    ]
