# Generated by Django 5.2.17 on 2026-10-01 09:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_domain', '0002_publicholiday_attendanceadjustment'),
        ('people_domain', '0006_add_assetcontrol_product_entitlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEmployeeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_code', models.CharField(max_length=64, unique=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='people_domain.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceImport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('month', models.DateField()),
                ('source', models.JSONField()),
                ('baseline', models.JSONField(default=dict)),
                ('mappings', models.JSONField(default=dict)),
                ('committed_at', models.DateTimeField(null=True)),
                ('replaced_count', models.PositiveIntegerField(default=0)),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('data', models.JSONField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave_domain.attendanceimport')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people_domain.employee')),
            ],
            options={
                'ordering': ['employee__employee_code', 'date'],
                'permissions': [('import_attendance', 'Can import HR attendance exports'), ('view_own_actual_attendance', 'Can view own imported attendance'), ('view_team_actual_attendance', 'Can view imported attendance in led teams')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_actual_attendance_day')],
            },
        ),
    ]
