# Generated by Django 5.2.17 on 2026-10-03 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_domain', '0004_attendance_permissions'),
        ('people_domain', '0006_add_assetcontrol_product_entitlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='end_period',
            field=models.CharField(choices=[('am', 'Sáng'), ('pm', 'Chiều')], default='pm', max_length=2),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_period',
            field=models.CharField(choices=[('am', 'Sáng'), ('pm', 'Chiều')], default='am', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date')), ('start_period', 'am'), ('end_period', 'pm'), _connector='OR'), name='leave_period_order'),
        ),
    ]
