# Generated by Django 5.2.17 on 2026-10-01 08:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people_domain', '0006_add_assetcontrol_product_entitlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('finalized', 'Đã chốt'), ('acknowledged', 'Đã xác nhận')], default='draft', max_length=16)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('leader_comment', models.TextField(blank=True)),
                ('employee_feedback', models.TextField(blank=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_reviews', to='people_domain.employee')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_reviews', to='people_domain.employee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people_domain.team')),
            ],
            options={
                'ordering': ['-month', 'employee__employee_code'],
                'permissions': [('manage_team_reviews', 'Create and score reviews in led teams'), ('view_company_reviews', 'Read company performance reviews'), ('reopen_reviews', 'Reopen finalized reviews'), ('view_own_reviews', 'Read and acknowledge own finalized reviews')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceKPI',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('completion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comment', models.TextField(blank=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='performance_domain.performancereview')),
            ],
            options={
                'ordering': ['position', 'uuid'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReviewRevision',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='performance_domain.performancereview')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='performancereview',
            constraint=models.UniqueConstraint(fields=('employee', 'month'), name='unique_employee_review_month'),
        ),
        migrations.AddConstraint(
            model_name='performancekpi',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0), ('weight__lte', 100)), name='kpi_weight_range'),
        ),
        migrations.AddConstraint(
            model_name='performancekpi',
            constraint=models.CheckConstraint(condition=models.Q(('completion__isnull', True), models.Q(('completion__gte', 0), ('completion__lte', 100)), _connector='OR'), name='kpi_completion_range'),
        ),
    ]
