/* Synthetic, deterministic records. Shared identity below is a fixture, not a production deduplication rule. */
const names = ['Nguyễn Minh Anh', 'Trần Quốc Bảo', 'Lê Thu Hà', 'Phạm Đức Long', 'Vũ Ngọc Mai', 'Đỗ Tuấn Kiệt', 'Hoàng Thanh Tâm', 'Bùi Gia Linh', 'Đặng Hải Nam', 'Phan Ngọc Hân'];
const products = [{name:'Bình giữ nhiệt 500 ml', price:249000}, {name:'Đèn bàn học',price:389000}, {name:'Bộ hộp thực phẩm',price:179000}, {name:'Gối tựa lưng',price:299000}, {name:'Kệ để bàn',price:459000}];
const deliveryStates = ['Giao thành công', 'Giao thành công', 'Đang giao', 'Chưa bàn giao', 'Hoàn hàng', 'Đã hủy'];
const sources = ['Webcake','POS','Google Sheet'];
const orders = Array.from({length:60},(_,i)=>{
  const product=products[i%products.length], quantity=1+i%3, delivery=deliveryStates[i%6];
  const origin=sources[i%3];
  return {id:`DEMO-${String(i+1).padStart(4,'0')}`,date:`2026-10-${String(1+Math.floor(i/2)).padStart(2,'0')}`,name:names[i%10],phone:`SĐT giả ${String(i+1).padStart(4,'0')}`,address:`Địa chỉ minh họa ${i+1}, không dùng giao hàng`,product:product.name,price:product.price,quantity,value:product.price*quantity,delivery,processing:delivery==='Chưa bàn giao'?'Chờ xác nhận':delivery==='Đã hủy'?'Đã hủy':'Đã xác nhận',payment:delivery==='Giao thành công'?'Chờ đối soát COD':delivery==='Hoàn hàng'||delivery==='Đã hủy'?'Không thu':'Chưa thu',origin,sources:i%5===0?[origin,sources[(i%3+1)%3]]:[origin]};
});
window.crmDemo={orders};
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(n);
const number=n=>new Intl.NumberFormat('vi-VN').format(n);
const date=s=>s.split('-').reverse().join('/');
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge=s=>`<span class="badge ${s==='Giao thành công'?'good':s==='Hoàn hàng'||s==='Đã hủy'?'bad':s==='Đang giao'?'warning':''}">${escapeHtml(s)}</span>`;
let page=1, selected=null, lastFocus=null;
const pageSize=12;
const descriptions={orders:['Quản lý đơn hàng','Một đơn có thể có nhiều bản ghi nguồn. Xem đơn trước, kiểm tra dữ liệu sau.'],reports:['Thống kê đơn hàng','Báo cáo tính từ cùng tập đơn đã lọc; chưa phải doanh thu kế toán.'],ads:['Chi phí & hiệu quả quảng cáo','Phác thảo dữ liệu cần có để nối chi phí quảng cáo với kết quả bán hàng.'],accounting:['Kế toán & đối soát','Phác thảo đối soát tiền và chi phí với đơn vị kho vận bên thứ ba.'],review:['Nội dung cần duyệt','Dùng bản mẫu để trao đổi với Leader, người xử lý đơn và kế toán.']};
function route(){return location.hash.slice(1)||'orders'}
function filtered(){const query=$('search').value.trim().toLocaleLowerCase('vi');return orders.filter(o=>(!query||`${o.id} ${o.name} ${o.product}`.toLocaleLowerCase('vi').includes(query))&&(!$('from').value||o.date>=$('from').value)&&(!$('to').value||o.date<=$('to').value)&&(!$('source').value||o.sources.includes($('source').value))&&(!$('status').value||o.delivery===$('status').value));}
function reset(){ $('search').value='';$('from').value='2026-10-01';$('to').value='2026-10-30';$('source').value='';$('status').value='';page=1;render();}
function summary(rows){return {count:rows.length,value:rows.reduce((n,o)=>n+o.value,0),delivered:rows.filter(o=>o.delivery==='Giao thành công'),returned:rows.filter(o=>o.delivery==='Hoàn hàng'),cancelled:rows.filter(o=>o.delivery==='Đã hủy')};}
function render(){const key=route(), info=descriptions[key];document.querySelectorAll('[data-page]').forEach(a=>{a.classList.toggle('selected',a.dataset.page===key);if(a.dataset.page===key)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});$('page-title').textContent=info?.[0]||'Không tìm thấy trang';$('page-description').textContent=info?.[1]||'Chọn một mục trong menu để tiếp tục.';$('filters').hidden=!['orders','reports'].includes(key);const rows=filtered();if(key==='orders')renderOrders(rows);else if(key==='reports')renderReports(rows);else if(key==='review')renderReview();else if(info)renderRequirements(key);else $('content').innerHTML='<div class="empty"><h2>Trang này chưa có</h2><a href="#orders">Trở về đơn hàng</a></div>'; $('announcer').textContent=`${info?.[0]||'Không tìm thấy trang'}. ${rows.length} đơn trong bộ lọc.`;}
function renderOrders(rows){const totalPages=Math.max(1,Math.ceil(rows.length/pageSize));page=Math.min(page,totalPages);const sum=summary(rows),records=rows.reduce((n,o)=>n+o.sources.length,0);$('content').innerHTML=`<div class="ledger-summary"><div><strong>${rows.length} đơn</strong> <span class="muted">/ ${records} bản ghi nguồn</span></div><div>Giá trị đơn <strong>${money(sum.value)}</strong></div></div>${rows.length?`<div class="table-wrap"><table><caption class="sr-only">Danh sách đơn minh họa</caption><thead><tr><th>Mã đơn / Ngày</th><th>Khách hàng</th><th>Sản phẩm</th><th class="number">Giá trị</th><th>Nguồn dữ liệu</th><th>Giao hàng</th></tr></thead><tbody>${rows.slice((page-1)*pageSize,page*pageSize).map(o=>`<tr data-order="${o.id}" class="${selected===o.id?'chosen':''}"><td><button class="order-link" data-open="${o.id}" aria-label="Xem chi tiết ${o.id}">${o.id}</button><small>${date(o.date)}</small></td><td>${escapeHtml(o.name)}<small>${escapeHtml(o.phone)}</small></td><td>${escapeHtml(o.product)}<small>Số lượng: ${o.quantity}</small></td><td class="number">${money(o.value)}</td><td class="sources">${o.origin}${o.sources.length>1?'<em>+1 nguồn</em>':''}</td><td>${badge(o.delivery)}</td></tr>`).join('')}</tbody></table></div><div class="pagination"><span>${(page-1)*pageSize+1}–${Math.min(page*pageSize,rows.length)} / ${rows.length} đơn</span><div><button id="prev" ${page===1?'disabled':''}>Trước</button><span>Trang ${page} / ${totalPages}</span><button id="next" ${page===totalPages?'disabled':''}>Sau</button></div></div>`:'<div class="empty"><h2>Không có đơn phù hợp</h2><p>Thử đổi từ khóa, thời gian hoặc trạng thái.</p><button id="empty-reset">Đặt lại bộ lọc</button></div>'}<p class="source-note"><strong>Đếm một lần cho mỗi đơn minh họa.</strong> 12 đơn có bản ghi ở hai nguồn. Việc nhận ra chúng là cùng một đơn đã được khai báo trong dữ liệu giả; quy tắc đối chiếu dữ liệu thật chưa được chốt. Lọc nguồn chỉ chọn đơn có mặt ở nguồn đó.</p>`;document.querySelectorAll('[data-order]').forEach(row=>row.addEventListener('click',()=>openDetail(row.dataset.order)));$('prev')?.addEventListener('click',()=>{page--;render()});$('next')?.addEventListener('click',()=>{page++;render()});$('empty-reset')?.addEventListener('click',reset);}
function openDetail(id){lastFocus=document.querySelector(`[data-open="${id}"]`);selected=id;const o=orders.find(o=>o.id===id);$('detail-content').innerHTML=`<div class="detail-heading"><div><h2 id="detail-title">${o.id}</h2><p class="intro">${date(o.date)} · Đơn minh họa</p></div><button id="close-detail" class="close" aria-label="Đóng chi tiết đơn">Đóng <span aria-hidden="true">×</span></button></div><dl class="facts"><div><dt>Khách hàng</dt><dd>${escapeHtml(o.name)}</dd></div><div><dt>Điện thoại</dt><dd>${o.phone}</dd></div><div><dt>Địa chỉ</dt><dd>${o.address}</dd></div><div><dt>Nguồn tạo bản ghi đầu tiên</dt><dd>${o.origin}</dd></div></dl><h3>Sản phẩm & giá trị đơn</h3><div class="table-wrap"><table><thead><tr><th>Sản phẩm</th><th class="number">SL</th><th class="number">Thành tiền</th></tr></thead><tbody><tr><td>${o.product}<small>${money(o.price)} / sản phẩm</small></td><td class="number">${o.quantity}</td><td class="number">${money(o.value)}</td></tr></tbody></table></div><div class="status-list"><div><span>Xử lý đơn</span>${badge(o.processing)}</div><div><span>Giao hàng</span>${badge(o.delivery)}</div><div><span>Thanh toán</span>${badge(o.payment)}</div></div><h3>Bản ghi nguồn (${o.sources.length})</h3>${o.sources.map((s,i)=>`<div class="source-evidence"><strong>${s}</strong><span>Mã giả: ${s==='Webcake'?'WC':s==='POS'?'POS':'SHEET'}-${o.id.slice(-4)}${i?' · Bản ghi bổ sung':''}</span></div>`).join('')}<p class="intro">${o.sources.length>1?'Hai bản ghi đã được gắn vào cùng một đơn trong fixture. Không cộng thêm một đơn vào báo cáo.':'Đơn này có một bản ghi nguồn trong dữ liệu minh họa.'}</p><h2>Lịch sử minh họa</h2><ol class="timeline"><li>Tạo bản ghi từ ${o.origin}<small>${date(o.date)} · 09:00</small></li>${o.sources.length>1?`<li>Có thêm bản ghi từ ${o.sources[1]}<small>${date(o.date)} · 09:15 · Liên kết được khai báo sẵn</small></li>`:''}<li>Trạng thái hiện tại: ${o.delivery}<small>Ví dụ để duyệt cách hiển thị; chưa mô tả quy trình thực tế.</small></li></ol><div class="detail-foot">Chỉ xem minh họa. Chưa có thao tác xác nhận đơn, chuyển kho, sửa trạng thái hay lưu dữ liệu.</div>`;$('detail').hidden=false;document.body.classList.add('detail-open');if(matchMedia('(max-width:700px)').matches){document.querySelector('.shell').inert=true;document.querySelector('.product-bar').inert=true}render();$('close-detail').addEventListener('click',closeDetail);$('close-detail').focus();}
function closeDetail(){selected=null;$('detail').hidden=true;document.body.classList.remove('detail-open');document.querySelector('.shell').inert=false;document.querySelector('.product-bar').inert=false;render();const restored=lastFocus?.dataset.open?document.querySelector(`[data-open="${lastFocus.dataset.open}"]`):null;(restored||$('main')).focus();}
function group(rows,key){const map=new Map();for(const o of rows){const k=o[key];if(!map.has(k))map.set(k,{name:k,count:0,value:0,delivered:0});const g=map.get(k);g.count++;g.value+=o.value;if(o.delivery==='Giao thành công')g.delivered++}return [...map.values()]}
function reportTable(groups,heading){return `<div><h2>${heading}</h2><div class="table-wrap"><table><thead><tr><th>${heading==='Theo sản phẩm'?'Sản phẩm':'Nguồn đầu tiên'}</th><th class="number">Đơn</th><th class="number">Giá trị</th><th class="number">Đã giao</th></tr></thead><tbody>${groups.map(g=>`<tr><td>${g.name}</td><td class="number">${g.count}</td><td class="number">${money(g.value)}</td><td class="number">${g.delivered}</td></tr>`).join('')}</tbody></table></div></div>`}
function renderReports(rows){const s=summary(rows),pct=n=>s.count?`${(n/s.count*100).toFixed(1).replace('.',',')}%`:'—';const metrics=[['Số đơn',number(s.count),'Mỗi đơn minh họa đếm một lần'],['Giá trị đơn',money(s.value),'Tổng giá trị sản phẩm trong đơn'],['Giá trị đã giao',money(s.delivered.reduce((n,o)=>n+o.value,0)),'Chưa đồng nghĩa tiền đã nhận'],['Trung bình mỗi đơn',s.count?money(s.value/s.count):'—','Giá trị đơn / số đơn'],['Giao thành công',pct(s.delivered.length),`${s.delivered.length} / ${s.count} đơn`],['Hoàn hàng',pct(s.returned.length),`${s.returned.length} / ${s.count} đơn`],['Hủy đơn',pct(s.cancelled.length),`${s.cancelled.length} / ${s.count} đơn`],['Bản ghi nguồn',number(rows.reduce((n,o)=>n+o.sources.length,0)),'Không dùng làm số đơn']];const days=group(rows,'date');$('content').innerHTML=`<p class="muted">${s.count} đơn trong bộ lọc hiện tại. Trạng thái là snapshot minh họa.</p><dl class="metrics">${metrics.map(([label,value,note])=>`<div class="metric"><dt>${label}</dt><dd>${value}<small>${note}</small></dd></div>`).join('')}</dl>${rows.length?`<div class="report-grid">${reportTable(group(rows,'origin'),'Theo nguồn dữ liệu')}${reportTable(group(rows,'product'),'Theo sản phẩm')}</div><h2>Số đơn theo ngày</h2><div class="bars">${days.map(g=>`<div class="bar-row"><span>${date(g.name)}</span><div class="bar-track"><span style="width:${g.count/Math.max(...days.map(x=>x.count))*100}%"></span></div><strong class="number">${g.count}</strong></div>`).join('')}</div>`:'<div class="empty"><h2>Không có dữ liệu trong bộ lọc</h2><button id="empty-reset">Đặt lại bộ lọc</button></div>'}<details class="definitions"><summary>Cách tính & cách tránh đếm trùng trong bản mẫu</summary><p>Trọng số theo nguồn dùng nguồn tạo bản ghi đầu tiên, mỗi đơn thuộc một nhóm. Đây là quy ước trình bày demo, chưa phải nguồn chuẩn được duyệt. Tỷ lệ giao / hoàn / hủy = số đơn ở trạng thái tương ứng chia toàn bộ số đơn đã lọc, kể cả đơn đang xử lý. Khi tập đơn rỗng, tỷ lệ và trung bình hiển thị “—”. Giá trị đơn không gồm phí vận chuyển, giảm giá hay hoàn tiền.</p></details><h2>Chỉ số cần thêm dữ liệu</h2><div class="table-wrap"><table><thead><tr><th>Chỉ số</th><th>Dữ liệu còn thiếu</th><th>Trạng thái</th></tr></thead><tbody><tr><td>ROAS</td><td>Chi phí quảng cáo, quy tắc gắn đơn với chiến dịch và cơ sở doanh thu</td><td>${badge('Cần thêm dữ liệu')}</td></tr><tr><td>Chi phí mỗi đơn</td><td>Chi phí quảng cáo cùng kỳ, cách phân bổ và tập đơn được tính</td><td>${badge('Cần thêm dữ liệu')}</td></tr><tr><td>Lợi nhuận</td><td>Giá vốn, phí kho vận, quảng cáo, hoàn hàng và các chi phí khác</td><td>${badge('Cần thêm dữ liệu')}</td></tr><tr><td>COD chưa nhận</td><td>Tiền thu hộ dự kiến, bảng chuyển tiền và kết quả đối soát</td><td>${badge('Cần thêm dữ liệu')}</td></tr></tbody></table></div>`;$('empty-reset')?.addEventListener('click',reset);}
function renderRequirements(key){const ads=key==='ads';$('content').innerHTML=`<section class="requirements"><h2>${ads?'Nối chi phí với kết quả bán hàng':'Biết khoản nào đã nhận, khoản nào còn chênh lệch'}</h2><p>${ads?'Dữ liệu đơn hàng là một phần. Cần xác định cách ghi nhận chi phí và quy tắc gắn đơn với quảng cáo trước khi tính hiệu quả.':'Kho vận do bên thứ ba vận hành. Cần bảng đối soát của họ và quy tắc kế toán được duyệt để đối chiếu với đơn.'}</p><h3>Dữ liệu cần chuẩn bị</h3><ul>${(ads?['Chi phí theo ngày, tài khoản và chiến dịch quảng cáo.','Mã liên kết chiến dịch / nguồn bán với đơn; cách xử lý đơn không xác định được nguồn.','Cơ sở doanh thu: giá trị tạo đơn, giao thành công hay tiền thực nhận.','Quyền xem chi phí và hiệu quả theo nhân sự / Team.']:['Bảng thu hộ COD, mã vận đơn và kỳ chuyển tiền.','Phí giao hàng, lưu kho, hoàn hàng và các khoản khấu trừ.','Giá vốn, giảm giá, hoàn tiền và chứng từ liên quan.','Ai đối soát, ai duyệt chênh lệch và thời điểm khóa kỳ.']).map(t=>`<li>${t}</li>`).join('')}</ul><p><span class="badge warning">Chưa kết nối · Chưa có nghiệp vụ</span></p><a href="#review">Xem nội dung cần Leader xác nhận →</a></section>`;}
function renderReview(){$('content').innerHTML=`<div class="review-sheet"><section><h2>Quy trình xử lý đơn thực tế</h2><p>Nhờ một người đang xử lý đơn mô tả một đơn từ lúc phát sinh đến giao thành công hoặc hoàn/hủy.</p><ul><li>Ai xác nhận đơn? Ai chuyển cho kho bên thứ ba?</li><li>Nhân sự thao tác ở Webcake, POS hay Sheet trong từng bước?</li><li>Khi giao thất bại, hoàn hàng hoặc sửa đơn, dữ liệu được cập nhật ở đâu?</li></ul></section><section><h2>Nguồn chuẩn & đơn xuất hiện nhiều nơi</h2><p>Một đơn qua ba nguồn vẫn cần được hiểu là một đơn; chưa chốt cách nhận dạng bằng dữ liệu thật.</p><ul><li>Webcake, POS và Sheet có dùng chung mã đơn không?</li><li>Nếu giá trị hoặc trạng thái khác nhau, lấy dữ liệu từ đâu?</li><li>Ai kiểm tra trường hợp chưa rõ hoặc nghi trùng?</li></ul></section><section><h2>Quyền xem & thao tác</h2><p>Chưa suy ra quyền CRM từ quyền MRERP hiện có.</p><ul><li>Ads, người xử lý đơn, Leader và kế toán được xem những trường nào?</li><li>Ai được sửa đơn, xem thông tin khách, xem chi phí và xuất dữ liệu?</li><li>Phạm vi quyền theo Team, nhân sự, shop hay toàn công ty?</li></ul></section><section><h2>Sau buổi duyệt</h2><p>Chuẩn bị mẫu đã ẩn thông tin khách từ cả ba nguồn, một bảng kho vận / COD và một bảng chi phí quảng cáo. Chốt định nghĩa chỉ số trước khi xây nhập dữ liệu và báo cáo thật.</p></section></div>`;}
for(const id of ['search','from','to','source','status'])$(id).addEventListener(id==='search'?'input':'change',()=>{page=1;if(selected)closeDetail();else render()});
$('reset').addEventListener('click',()=>{if(selected)closeDetail();reset()});
window.addEventListener('hashchange',()=>{if(selected)closeDetail();render();$('main').focus()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&selected)closeDetail()});
render();
