# Generated by Django 5.2.17 on 2026-08-28 04:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('target_type', models.CharField(max_length=80)),
                ('target_uuid', models.CharField(blank=True, max_length=64)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Mã nhân sự phải gồm 3 chữ cái viết hoa và số thứ tự, ví dụ NDK13.', regex='^[A-Z]{3}\\d+$')])),
                ('display_name', models.CharField(blank=True, max_length=160)),
                ('national_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('rank', models.CharField(choices=[('staff', 'Staff'), ('captain', 'Captain'), ('leader', 'Leader'), ('manager', 'Manager'), ('ceo', 'CEO')], default='staff', max_length=16)),
                ('employment_status', models.CharField(choices=[('probation', 'Thử việc'), ('official', 'Chính thức')], default='probation', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='people_domain.department')),
                ('identity_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_code'],
                'permissions': [('view_company_directory', 'Can view the company directory'), ('view_hr_detail', 'Can view HR-only employee details'), ('promote_employee', 'Can promote probation employees'), ('manage_organization', 'Can manage departments and teams'), ('manage_membership', 'Can manage team membership and leadership'), ('view_people_audit', 'Can view People audit events')],
            },
        ),
        migrations.CreateModel(
            name='EmploymentTransition',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('probation', 'Thử việc'), ('official', 'Chính thức')], max_length=16)),
                ('to_status', models.CharField(choices=[('probation', 'Thử việc'), ('official', 'Chính thức')], max_length=16)),
                ('note', models.TextField()),
                ('effective_at', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employment_transitions', to='people_domain.employee')),
            ],
            options={
                'ordering': ['-effective_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='people_domain.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='people_domain.team'),
        ),
        migrations.CreateModel(
            name='TeamLeadership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_team_links', to='people_domain.employee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderships', to='people_domain.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'leader'), name='unique_team_leader')],
            },
        ),
    ]
