# Generated by Django 5.2.17 on 2026-08-29 04:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_domain', '0004_flat_team_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_code'], 'permissions': [('view_company_directory', 'Can view the company directory'), ('view_hr_detail', 'Can view HR-only employee details'), ('promote_employee', 'Can promote probation employees'), ('promote_any_employee', 'Can promote probation employees across the company'), ('manage_organization', 'Can manage departments and teams'), ('manage_membership', 'Can manage team membership and leadership'), ('view_people_audit', 'Can view People audit events'), ('change_own_profile', 'Can change allowed fields on own profile'), ('change_own_password', 'Can change own account password'), ('provision_employee_account', 'Can provision an account for an employee'), ('manage_employee_account', 'Can lock and unlock employee accounts'), ('reset_employee_password', 'Can reset employee account passwords'), ('change_employment_status', 'Can pause, terminate and reactivate employment'), ('import_export_employee', 'Can import and export employees'), ('view_people_admin_panel', 'Can view People access administration'), ('manage_people_access', 'Can manage People access bundles')]},
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('probation', 'Thử việc'), ('official', 'Chính thức'), ('paused', 'Tạm nghỉ'), ('terminated', 'Nghỉ việc')], default='probation', max_length=16),
        ),
        migrations.AlterField(
            model_name='employmenttransition',
            name='from_status',
            field=models.CharField(choices=[('probation', 'Thử việc'), ('official', 'Chính thức'), ('paused', 'Tạm nghỉ'), ('terminated', 'Nghỉ việc')], max_length=16),
        ),
        migrations.AlterField(
            model_name='employmenttransition',
            name='to_status',
            field=models.CharField(choices=[('probation', 'Thử việc'), ('official', 'Chính thức'), ('paused', 'Tạm nghỉ'), ('terminated', 'Nghỉ việc')], max_length=16),
        ),
        migrations.CreateModel(
            name='EmployeeAccountState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=False)),
                ('revoked_group_names', models.JSONField(blank=True, default=list)),
                ('previous_active_status', models.CharField(blank=True, choices=[('probation', 'Thử việc'), ('official', 'Chính thức'), ('paused', 'Tạm nghỉ'), ('terminated', 'Nghỉ việc')], max_length=16, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_state', to='people_domain.employee')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembershipHistory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_at', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_membership_history', to='people_domain.employee')),
                ('from_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membership_history_from', to='people_domain.team')),
                ('to_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membership_history_to', to='people_domain.team')),
            ],
            options={
                'ordering': ['-effective_at'],
            },
        ),
    ]
