import { expect, test } from '@playwright/test'
import fs from 'node:fs'
import { execFileSync } from 'node:child_process'
import path from 'node:path'

test('HR nhập Excel → Leader xem Team → Staff xem công của mình', async ({ page }) => {
  // Create a synthetic fixture through the backend test helper, never real HR data.
  const root = path.resolve('../../..')
  const localPython = path.join(root, '.venv', process.platform === 'win32' ? 'Scripts/python.exe' : 'bin/python')
  const python = process.env.E2E_PYTHON ?? (fs.existsSync(localPython) ? localPython : 'python')
  const file = path.join(root, 'tmp/attendance-e2e-fixture.xlsx')
  execFileSync(python, ['-c', "import django; django.setup(); from leave_domain.test_attendance_import import fixture_bytes; from pathlib import Path; Path('tmp').mkdir(exist_ok=True); Path('tmp/attendance-e2e-fixture.xlsx').write_bytes(fixture_bytes(second=True))"], { cwd: root, env: { ...process.env, PYTHONPATH: path.join(root, 'apps/mrerp/backend'), DJANGO_SETTINGS_MODULE: 'config.settings' } })
  await page.goto('/')
  await page.getByLabel('Tài khoản', { exact: true }).fill('hr.demo')
  await page.getByLabel('Mật khẩu', { exact: true }).fill(process.env.E2E_DEMO_PASSWORD ?? 'Playwright-Only-1234!')
  await page.getByRole('button', { name: 'Đăng nhập MRERP' }).click()
  await page.getByRole('button', { name: 'Nghỉ & Công', exact: true }).click()
  await page.getByRole('button', { name: 'Chấm công', exact: true }).click()
  await page.getByLabel('Chọn file Excel').setInputFiles(file)
  await expect(page.getByRole('heading', { name: 'Xem trước tháng 2026-09' })).toBeVisible()
  const first = page.getByLabel('Ghép mã 00001')
  const second = page.getByLabel('Ghép mã 00002')
  if (await first.isEnabled()) await first.selectOption(await first.locator('option').filter({ hasText: 'STF01 ·' }).getAttribute('value') ?? '')
  if (await second.isEnabled()) await second.selectOption(await second.locator('option').filter({ hasText: 'OTH01 ·' }).getAttribute('value') ?? '')
  const replace = page.getByRole('checkbox', { name: /Tôi xác nhận thay thế/ })
  if (await replace.count()) await replace.check()
  fs.mkdirSync(path.join(root, '.impeccable/review'), { recursive: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: path.join(root, '.impeccable/review/attendance-preview-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: path.join(root, '.impeccable/review/attendance-preview-mobile.png'), fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('button', { name: 'Xác nhận nhập công', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Đã nhập 4 dòng' })).toBeVisible()
  await expect(page.locator('.actual-grid')).toContainText('Staff Beta')
  await page.getByRole('button', { name: 'Staff Alpha, ngày 2026-09-07, 0,5 công', exact: true }).click()
  await expect(page.locator('.actual-detail')).toContainText('08:00 → 12:00')
  await expect(page.locator('.actual-detail')).toContainText('3,48')
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: path.join(root, '.impeccable/review/attendance-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: path.join(root, '.impeccable/review/attendance-mobile.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('button', { name: 'Đóng chi tiết', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Staff Alpha, ngày 2026-09-07, 0,5 công', exact: true })).toBeFocused()
  await expect(page.getByRole('button', { name: 'Chấm công', exact: true })).toHaveAttribute('aria-pressed', 'true')
  for (const persona of ['leader.demo', 'staff.demo']) {
    await page.getByLabel('Xem theo vai trò debug').selectOption(persona)
    await expect(page.getByLabel('Xem theo vai trò debug')).toHaveValue(persona)
    await page.getByRole('button', { name: 'Nghỉ & Công', exact: true }).click()
    await page.getByRole('button', { name: 'Chấm công', exact: true }).click()
    await page.getByLabel('Tháng chấm công').fill('2026-09')
    await expect(page.locator('.actual-grid')).toContainText('Staff Alpha')
    await expect(page.locator('.actual-grid')).not.toContainText('Staff Beta')
    await expect(page.getByLabel('Chọn file Excel')).toHaveCount(0)
  }
})
