import {expect,test,Page} from '@playwright/test'
async function login(page:Page,name:string){await page.goto('/');await page.getByLabel('Tài khoản',{exact:true}).fill(name);await page.getByLabel('Mật khẩu',{exact:true}).fill(process.env.E2E_DEMO_PASSWORD??'Playwright-Only-1234!');await page.getByRole('button',{name:'Đăng nhập MRERP'}).click();await expect(page.getByLabel('Xem theo vai trò debug')).toBeVisible()}
async function persona(page:Page,name:string){await page.getByLabel('Xem theo vai trò debug').selectOption(name);await expect(page.getByLabel('Xem theo vai trò debug')).toHaveValue(name)}
async function capture(page:Page,_name:string){for(const [width,height] of [[1440,1000],[390,844]]){await page.setViewportSize({width,height});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()}await page.setViewportSize({width:1440,height:1000})}

test('KPI sao chép cấu trúc → chốt → xác nhận → mở lại',async({page})=>{
 await login(page,'leader.demo');await page.getByRole('button',{name:'Đánh giá nhân sự',exact:true}).click();await page.getByLabel('Tháng đánh giá',{exact:true}).fill('2026-10');await page.getByRole('button',{name:'Đánh giá Staff Alpha',exact:true}).click();
 await page.getByRole('button',{name:'Sao chép KPI tháng trước'}).click();await expect(page.getByLabel('Tên KPI 1',{exact:true})).toHaveValue('Hiệu quả chiến dịch');await expect(page.getByLabel('Hoàn thành KPI 1',{exact:true})).toHaveValue('');await expect(page.getByLabel('Nhận xét tổng kết',{exact:true})).toHaveValue('');
 await page.getByLabel('Hoàn thành KPI 1',{exact:true}).fill('85');await page.getByLabel('Nhận xét tổng kết',{exact:true}).fill('Hoàn thành mục tiêu chiến dịch.');await capture(page,'performance');await page.getByRole('button',{name:'Chốt đánh giá',exact:true}).click();await expect(page.locator('.performance-panel > header')).toContainText('Đã chốt');await expect(page.locator('.performance-panel')).toContainText('85.00 / 100');
 await persona(page,'staff.demo');await page.getByRole('button',{name:'Đánh giá nhân sự',exact:true}).click();await page.getByLabel('Tháng đánh giá',{exact:true}).fill('2026-10');await page.getByRole('button',{name:'Xem Staff Alpha',exact:true}).click();await page.getByLabel('Phản hồi của tôi').fill('Đã đọc kết quả.');await page.getByRole('button',{name:'Xác nhận đã đọc'}).click();await expect(page.locator('.performance-panel')).toContainText('Đã xác nhận');
 await persona(page,'hr.demo');await page.getByRole('button',{name:'Đánh giá nhân sự',exact:true}).click();await page.getByLabel('Tháng đánh giá',{exact:true}).fill('2026-10');await page.getByRole('button',{name:'Xem Staff Alpha',exact:true}).click();await page.getByLabel('Lý do mở lại').fill('Rà soát mục tiêu');await page.getByRole('button',{name:'Mở lại phiếu'}).click();await expect(page.locator('.performance-panel')).toContainText('Bản nháp');await page.getByText(/Lịch sử chốt và mở lại/).click();await expect(page.locator('.review-revision').last()).toContainText('Đã đọc kết quả.');
})

test('Lịch phỏng vấn, ghi chú, bộ lọc và lịch sử pipeline',async({page})=>{
 await login(page,'leader.demo');await page.getByRole('button',{name:'Tuyển dụng',exact:true}).click();await page.getByPlaceholder('Vị trí, ứng viên, email hoặc điện thoại').fill('Ứng viên demo Ads');await page.locator('.candidate-card').filter({hasText:'Ứng viên demo Ads'}).click();await page.getByLabel('Thời gian phỏng vấn').fill('2026-10-05T09:00');await page.getByLabel('Người phụ trách (tên)').fill('Leader Alpha');await page.getByLabel('Ghi chú nội bộ',{exact:true}).fill('Trao đổi kinh nghiệm tối ưu chiến dịch.');await page.getByRole('button',{name:'Lưu lịch & ghi chú'}).click();await expect(page.getByLabel('Ghi chú nội bộ',{exact:true})).toHaveValue('Trao đổi kinh nghiệm tối ưu chiến dịch.');await page.getByRole('button',{name:'Sàng lọc',exact:true}).click();await expect(page.locator('.candidate-inspector')).toContainText('Lịch sử xử lý (1)');await capture(page,'recruitment');await page.getByRole('button',{name:'Đóng chi tiết ứng viên'}).click();await page.getByPlaceholder('Vị trí, ứng viên, email hoặc điện thoại').fill('Không tồn tại');await expect(page.getByText('Không có ứng viên phù hợp bộ lọc.')).toBeVisible();
})

test('Nghỉ nửa ngày thứ Bảy → Leader duyệt → lịch riêng → công dự kiến',async({page})=>{
 await login(page,'staff.demo');await page.getByRole('button',{name:'Nghỉ & Công',exact:true}).click();await page.getByLabel('Từ ngày').fill('2026-10-03');await page.getByLabel('Đến ngày').fill('2026-10-03');await page.getByLabel('Từ buổi').selectOption('am');await page.getByLabel('Đến buổi').selectOption('am');await page.getByLabel('Lý do nghỉ').fill('Lý do riêng demo');await capture(page,'leave');await page.getByRole('button',{name:'Gửi đơn xin nghỉ'}).click();await expect(page.locator('.leave-ticket').filter({hasText:'Lý do riêng demo'})).toBeVisible();
 await persona(page,'leader.demo');await page.getByRole('button',{name:'Nghỉ & Công',exact:true}).click();await page.getByRole('button',{name:/Cần duyệt/}).click();await page.locator('.leave-ticket').filter({hasText:'Lý do riêng demo'}).getByRole('button',{name:'Duyệt',exact:true}).click();await page.getByLabel('Ghi chú duyệt nghỉ').fill('Đã bố trí công việc.');await page.getByRole('button',{name:'Xác nhận xử lý'}).click();await page.getByRole('button',{name:'Lịch nghỉ Team',exact:true}).click();await page.getByLabel('Tháng lịch nghỉ').fill('2026-10');await expect(page.locator('.leave-workspace .performance-table')).toContainText('Staff Alpha');await expect(page.locator('.leave-workspace')).not.toContainText('Lý do riêng demo');
 await persona(page,'hr.demo');await page.getByRole('button',{name:'Nghỉ & Công',exact:true}).click();await page.getByRole('button',{name:'Công dự kiến',exact:true}).click();await page.getByLabel('Tháng bảng công').fill('2026-10');const row=page.locator('.attendance-row').filter({hasText:'STF01'});await expect(row).toContainText('26.5');await expect(row).toContainText('0.5');
})
