import { expect, test } from '@playwright/test'

test('HR catalog and quota → Leader grant/recognition → Staff redeem → HR approve/fulfill',async({page})=>{
 test.setTimeout(90000)
 await page.goto('/')
 await page.getByLabel('Tài khoản',{exact:true}).fill('hr.demo')
 await page.getByLabel('Mật khẩu',{exact:true}).fill(process.env.E2E_DEMO_PASSWORD??'E2E-Rewards-Only-1234!')
 await page.getByRole('button',{name:'Đăng nhập MRERP'}).click()
 const workspace=()=>page.getByRole('button',{name:'Sao & Đổi thưởng',exact:true}).click()
 const persona=async(name:string)=>{await page.getByLabel('Xem theo vai trò debug').selectOption(name);await expect(page.getByLabel('Xem theo vai trò debug')).toHaveValue(name)}
 await workspace()
 await page.getByRole('button',{name:'Hạn mức Team',exact:true}).click()
 await page.getByRole('combobox',{name:'Team',exact:true}).selectOption({label:'Alpha'})
 await page.getByLabel('Hạn mức sao',{exact:true}).fill('1000')
 await page.getByRole('button',{name:'Lưu hạn mức',exact:true}).click()
 await expect(page.getByText('Đã lưu hạn mức.',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Quản lý quà',exact:true}).click()
 const title=`Sách kiểm thử ${Date.now()}`
 await page.getByLabel('Tên quà',{exact:true}).fill(title)
 await page.getByLabel('Số sao để đổi',{exact:true}).fill('20')
 await page.getByLabel('Số lượng còn có thể đổi',{exact:true}).fill('3')
 await page.getByLabel('Mở đổi',{exact:true}).check()
 await page.getByRole('button',{name:'Lưu quà',exact:true}).click()
 await expect(page.getByText('Đã lưu quà.',{exact:true})).toBeVisible()
 await persona('leader.demo');await workspace()
 await page.getByRole('button',{name:'Cấp sao',exact:true}).click()
 await page.getByRole('combobox',{name:'Nhân sự',exact:true}).selectOption({label:'Staff Alpha · Alpha'})
 await page.getByLabel('Số sao',{exact:true}).fill('100')
 await page.getByLabel('Lý do',{exact:true}).fill('Đóng góp trong tháng')
 await page.getByRole('button',{name:'Cấp / điều chỉnh sao',exact:true}).click()
 await expect(page.getByText('Đã ghi giao dịch sao.',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Đánh giá nhân sự',exact:true}).click()
 await page.getByRole('button',{name:'Đánh giá Staff Alpha',exact:true}).click()
 await page.locator('.employee-recognition summary').click()
 await page.getByLabel('Chủ đề ghi nhận',{exact:true}).fill('Hợp tác')
 await page.getByLabel('Đóng góp của nhân sự',{exact:true}).fill('Hỗ trợ chiến dịch mới')
 await page.getByRole('button',{name:'Ghi nhận đóng góp',exact:true}).click()
 await expect(page.locator('.employee-recognition article').filter({hasText:'Hỗ trợ chiến dịch mới'})).toBeVisible()
 await persona('staff.demo');await workspace()
 await expect(page.locator('.gift-item').filter({hasText:title})).toBeVisible()
 await page.screenshot({path:'../../../.impeccable/review/rewards-desktop.png',fullPage:true})
 await page.setViewportSize({width:390,height:844})
 await page.screenshot({path:'../../../.impeccable/review/rewards-mobile.png',fullPage:true})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
 await page.setViewportSize({width:1440,height:1000})
 await page.locator('.gift-item').filter({hasText:title}).getByRole('button',{name:'Đổi quà',exact:true}).click()
 await page.getByRole('button',{name:'Xác nhận đổi 20 sao',exact:true}).click()
 await expect(page.getByText('Đã gửi yêu cầu đổi quà.',{exact:true})).toBeVisible()
 await persona('hr.demo');await workspace()
 await page.getByRole('button',{name:'Yêu cầu đổi thưởng',exact:true}).click()
 const row=page.locator('.redemption-item').filter({hasText:title})
 await row.getByRole('button',{name:'Duyệt yêu cầu',exact:true}).click()
 await row.getByRole('button',{name:'Xác nhận đã trao quà',exact:true}).click()
 await expect(row).toContainText('Đã trao quà')
 await page.getByRole('button',{name:'Đánh giá nhân sự',exact:true}).click()
 await page.getByRole('button',{name:'Xem Staff Alpha',exact:true}).click()
 await page.locator('.employee-recognition summary').click()
 await expect(page.getByRole('button',{name:'Ghi nhận đóng góp',exact:true})).toBeVisible()
})
