# Generated by Django 5.2.17 on 2026-08-29 05:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people_domain', '0005_alter_employee_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('company_scope', models.BooleanField(default=False)),
                ('is_official', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_mode', models.CharField(blank=True, max_length=16)),
                ('audience_employees', models.ManyToManyField(blank=True, related_name='direct_feed_posts', to='people_domain.employee')),
                ('audience_teams', models.ManyToManyField(blank=True, related_name='feed_posts', to='people_domain.team')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feed_posts', to='people_domain.employee')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_feed_posts', to=settings.AUTH_USER_MODEL)),
                ('shared_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shares', to='feed_domain.post')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('share_post', 'Can share feed posts'), ('moderate_post', 'Can moderate all feed content'), ('publish_official_post', 'Can publish official company announcements')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_mode', models.CharField(blank=True, max_length=16)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feed_comments', to='people_domain.employee')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_feed_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='feed_domain.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feed_domain.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=240)),
                ('storage_key', models.CharField(max_length=300, unique=True)),
                ('content_type', models.CharField(max_length=160)),
                ('size', models.PositiveBigIntegerField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feed_domain.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('celebrate', 'Celebrate'), ('support', 'Support'), ('insightful', 'Insightful')], max_length=16)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to='people_domain.employee')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='feed_domain.comment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('comment', 'actor'), name='unique_comment_reaction_actor')],
            },
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('celebrate', 'Celebrate'), ('support', 'Support'), ('insightful', 'Insightful')], max_length=16)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to='people_domain.employee')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='feed_domain.post')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('post', 'actor'), name='unique_post_reaction_actor')],
            },
        ),
    ]
