# Generated by Django 5.2.17 on 2026-08-29 05:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people_domain', '0005_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('scope', models.CharField(choices=[('team', 'Team'), ('company', 'Công ty')], max_length=12)),
                ('period', models.CharField(choices=[('day', 'Ngày'), ('week', 'Tuần'), ('month', 'Tháng'), ('quarter', 'Quý')], max_length=12)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_goals', to='people_domain.employee')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='people_domain.team')),
            ],
            options={
                'ordering': ['-starts_on', 'title'],
                'permissions': [('manage_goals', 'Can manage goals for led teams'), ('manage_company_goals', 'Can manage company and all team goals')],
            },
        ),
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Hằng ngày'), ('weekly', 'Hằng tuần'), ('monthly', 'Hằng tháng')], max_length=12)),
                ('interval', models.PositiveSmallIntegerField(default=1)),
                ('start_at', models.DateTimeField()),
                ('next_occurrence_at', models.DateTimeField()),
                ('anchor_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deadline_offset_minutes', models.PositiveIntegerField(default=1440)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Đang chạy'), ('paused', 'Tạm dừng'), ('stopped', 'Đã dừng')], default='active', max_length=12)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_recurrences', to='people_domain.employee')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_recurrences', to='people_domain.employee')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurrences', to='task_domain.goal')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurrences', to='people_domain.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('manage_recurrences', 'Can manage recurring task series')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField()),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'Đang thực hiện'), ('pending_review', 'Chờ xác nhận'), ('completed', 'Đã hoàn thành'), ('rework', 'Yêu cầu làm lại')], default='in_progress', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_tasks', to='people_domain.employee')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to='people_domain.employee')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to='people_domain.employee')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='task_domain.goal')),
                ('recurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='task_domain.recurrence')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='people_domain.team')),
            ],
            options={
                'ordering': ['status', 'due_at'],
                'permissions': [('update_task_progress', 'Can update assigned task progress'), ('accept_task', 'Can accept or request rework'), ('view_team_tasks', 'Can view tasks in led teams'), ('view_company_tasks', 'Can view company tasks')],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('brief', 'Yêu cầu'), ('evidence', 'Kết quả')], max_length=12)),
                ('original_name', models.CharField(max_length=240)),
                ('storage_key', models.CharField(max_length=300, unique=True)),
                ('content_type', models.CharField(max_length=160)),
                ('size', models.PositiveBigIntegerField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='task_domain.task')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_attachments', to='people_domain.employee')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='goal_end_on_or_after_start'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='task_progress_0_100'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('recurrence__isnull', False)), fields=('recurrence', 'scheduled_for'), name='unique_recurrence_occurrence'),
        ),
    ]
