window.MRERP_PROJECT_STATUS = Object.freeze({
  updatedAt: "28/08/2026",
  overallPercent: 20,
  currentPhase: "Phase 1",
  currentPhaseName: "People/HR Foundation",
  calculation: {
    summary: "6 phase có trọng số bằng nhau; Phase 0 hoàn tất, Phase 1 đang triển khai People Foundation.",
    formula: "round((100% + 20% + 0% + 0% + 0% + 0%) / 6) = 20%",
    confidence: "Trung bình",
    note: "Đây là cách tính quản trị tạm thời. Trọng số và lịch mục tiêu chưa được duyệt thành KPI chính thức.",
  },
  quality: [
    { label: "Source of truth", value: 100, state: "Đã thiết lập" },
    { label: "Repository governance", value: 100, state: "CI đang xanh" },
    { label: "Visual prototype v1", value: 100, state: "Đã có bản xem" },
    { label: "People vertical slice", value: 70, state: "Đang kiểm chứng local" },
  ],
  phase0Gates: [
    { label: "Đường đọc chính và tài liệu chuyên sâu nhất quán", done: true },
    { label: "Bản đồ source of truth và glossary", done: true },
    { label: "Danh sách open decisions", done: true },
    { label: "ADR template và quy trình chấp nhận", done: true },
    { label: "Governance baseline và repository CI", done: true },
    { label: "Không scaffold production ngoài phạm vi được yêu cầu", done: true },
    { label: "Người sở hữu sản phẩm duyệt source of truth Phase 0", done: true },
    { label: "Repository checker và diff check thành công", done: true },
  ],
  phases: [
    { id: "P0", name: "Context & nền tài liệu", percent: 100, state: "Hoàn tất", tone: "done" },
    { id: "P1", name: "Vertical slice nền tảng", percent: 20, state: "Đang thực hiện", tone: "active" },
    { id: "P2", name: "Nghiệp vụ nội bộ", percent: 0, state: "Chưa bắt đầu", tone: "pending" },
    { id: "P3", name: "Văn hóa & nhân sự", percent: 0, state: "Chưa bắt đầu", tone: "pending" },
    { id: "P4", name: "Tích hợp hiện hữu", percent: 0, state: "Chưa bắt đầu", tone: "pending" },
    { id: "P5", name: "MRECRM tối thiểu", percent: 0, state: "Chưa bắt đầu", tone: "pending" },
  ],
  modules: [
    { id: "dashboard", name: "Dashboard", phase: "Phase 1–2", percent: 20, group: "prototype", ui: "Có prototype UI", delivery: "Chưa triển khai production", description: "Không gian cá nhân, Task, thông báo và snapshot chịu lỗi." },
    { id: "people", name: "People / HR", phase: "Phase 1", percent: 70, group: "active", ui: "UI nối API thật", delivery: "Đang kiểm chứng local", description: "Employee, Department, Team, employment status và Leader–Team; còn Identity/deployment production." },
    { id: "attendance", name: "Attendance / Leave", phase: "Phase 2", percent: 10, group: "planned", ui: "Đã có yêu cầu", delivery: "Chưa bắt đầu", description: "Đơn nghỉ, số công, lịch và dữ liệu cá nhân được phép." },
    { id: "approvals", name: "Approvals", phase: "Phase 2", percent: 20, group: "prototype", ui: "Có prototype UI", delivery: "Chưa triển khai production", description: "Workflow phê duyệt riêng theo từng loại yêu cầu." },
    { id: "tasks", name: "Tasks", phase: "Phase 1–2", percent: 20, group: "prototype", ui: "Có prototype UI", delivery: "Chưa triển khai production", description: "Nguồn Task chuẩn với List, Calendar và Kanban view." },
    { id: "rewards", name: "Recognition / Rewards", phase: "Phase 3", percent: 20, group: "prototype", ui: "Có prototype UI", delivery: "Chờ policy", description: "Ghi nhận, sao, bảng xếp hạng và đổi quyền lợi." },
    { id: "recruitment", name: "Recruitment", phase: "Phase 3", percent: 20, group: "prototype", ui: "Có prototype UI", delivery: "Chưa triển khai production", description: "Yêu cầu tuyển, ứng viên và pipeline tuyển dụng." },
    { id: "documents", name: "Documents", phase: "Phase 3", percent: 20, group: "prototype", ui: "Có prototype UI", delivery: "Chờ storage decision", description: "Thư viện, phân loại, upload và quyền xem tài liệu." },
    { id: "payroll", name: "Personal Payroll", phase: "Chưa xếp phase", percent: 10, group: "blocked", ui: "Đã có yêu cầu", delivery: "Chờ policy", description: "Lương cá nhân theo đúng chủ thể và capability." },
    { id: "reporting", name: "Reporting", phase: "Phase 5+", percent: 10, group: "planned", ui: "Đã có yêu cầu", delivery: "Chưa bắt đầu", description: "Báo cáo từ read model được phép, không join DB chéo." },
    { id: "admin", name: "Admin Panel", phase: "Phase 1", percent: 20, group: "blocked", ui: "Có prototype UI", delivery: "Chờ quyết định quyền", description: "Account, tổ chức, capability, audit và integration health." },
    { id: "settings", name: "Personal Settings", phase: "Phase 3", percent: 15, group: "planned", ui: "Có khung UI", delivery: "Chưa triển khai production", description: "Hồ sơ hiển thị, notification, security và preference." },
  ],
  ecosystem: [
    { name: "Identity contract", phase: "Phase 1", state: "Đã duyệt cho dev/test", blocker: "IdP production vẫn chưa chọn" },
    { name: "Permission foundation", phase: "Phase 1", state: "People slice đã duyệt", blocker: "Policy ngoài slice vẫn theo open decisions" },
    { name: "ASSETCONTROL integration", phase: "Phase 4", state: "Chưa bắt đầu", blocker: "Chưa audit/mapping/dual-run" },
    { name: "MREKANBAN transition", phase: "Phase 4", state: "Chưa bắt đầu", blocker: "Tương lai dài hạn chưa quyết định" },
    { name: "MRECRM application", phase: "Phase 5", state: "Chưa bắt đầu", blocker: "Cần ADR trước khi scaffold CRM" },
  ],
  nextGates: [
    "Nghiệm thu People/HR Foundation trên môi trường local.",
    "Refinement vertical slice kế tiếp.",
    "Chọn Identity Provider production bằng ADR riêng khi đến thời điểm.",
  ],
  decisionSummary: {
    open: 20,
    resolved: 6,
    priority: 1,
    priorityNote: "OD-19 vẫn mở cho provisioning với IdP production; mock Phase 1 đã được chốt.",
  },
  sources: [
    "docs/04-tieu-chi-nghiem-thu.md",
    "docs/06-ke-hoach-trien-khai.md",
    "docs/product/roadmap.md",
    "docs/product/business-requirements.md",
    "docs/product/backlog.md",
    "docs/product/stories/phase-1-task-vertical-slice.md",
    "docs/product/stories/phase-1-people-foundation.md",
    "docs/architecture/people-data-contract.md",
    "docs/architecture/people-authorization-matrix.md",
    "docs/architecture/task-authorization-matrix.md",
    "docs/testing/definition-of-ready.md",
    "docs/testing/phase-1-task-acceptance.md",
    "docs/testing/phase-1-people-acceptance.md",
    "docs/testing/phase-1-people-readiness.md",
    "docs/decisions/0002-task-authorization-baseline.md",
    "docs/decisions/0003-phase-1-application-stack.md",
    "docs/decisions/0004-mock-identity-context.md",
    "docs/decisions/0005-people-authorization-and-field-policy.md",
    "docs/decisions/0006-employee-account-provisioning.md",
    "docs/decisions/open-decisions.md",
  ],
});
