import { useCallback, useEffect, useRef, useState } from 'react'
import { api, request } from '../api'
import type { Session, StarBalance, RewardAudienceMember, LeaderboardRow } from '../types'
import './rewards-store.css'
type Gift={uuid:string;title:string;description:string;category:string;cost:number;stock:number;active:boolean}
type Redemption={uuid:string;employee:string;employee_name:string;gift_title:string;cost:number;status:string;status_label:string;note:string;created_at:string}
type Allowances={teams:{uuid:string;name:string}[];allowances:{team_uuid:string;team_name:string;month:string;limit:number;used:number}[]}
const suggestions=['Đồ uống tự chọn','Bữa trưa yêu thích','Vé xem phim','Voucher ăn uống','Voucher thể thao','Sách tự chọn','Khóa học chuyên môn','Hỗ trợ lệ phí chứng chỉ','Chuột làm việc','Bàn phím','Tai nghe','Hỗ trợ nâng cấp thiết bị']
async function allRedemptions() { const rows:Redemption[]=[]; let url:string|null='/api/v1/rewards/redemptions/'; while(url) { const parsed:URL=new URL(url,window.location.origin); const page:{results:Redemption[];next:string|null}=await request<{results:Redemption[];next:string|null}>(parsed.pathname+parsed.search); rows.push(...page.results); url=page.next; } return rows; }
const blank={title:'',description:'',category:'Hằng ngày',cost:0,stock:0,active:false}
export function RewardsWorkspace({session}:{session:Session}) {
 const manager=!!session.capabilities?.includes('rewards_domain.grant_stars_company'),grant=!!session.capabilities?.includes('rewards_domain.grant_stars_scoped')
 const [tab,setTab]=useState('gifts'),[gifts,setGifts]=useState<Gift[]>([]),[rows,setRows]=useState<Redemption[]>([]),[balance,setBalance]=useState<StarBalance & {held?:number}>({balance:0,ledger:[]})
 const [limits,setLimits]=useState<Allowances>({teams:[],allowances:[]}),[people,setPeople]=useState<RewardAudienceMember[]>([]),[ranking,setRanking]=useState<LeaderboardRow[]>([])
 const [period,setPeriod]=useState<'month'|'quarter'|'year'>('month'),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true)
 const [form,setForm]=useState(blank),[edit,setEdit]=useState(''),[selected,setSelected]=useState<Gift|null>(null),[notes,setNotes]=useState<Record<string,string>>({}),[search,setSearch]=useState('')
 const [star,setStar]=useState({employee_uuid:'',amount:1,reason:''}),[quota,setQuota]=useState({team_uuid:'',month:new Date().toLocaleDateString('sv-SE').slice(0,7),limit:0})
 const key=useRef(crypto.randomUUID()),starKey=useRef(crypto.randomUUID())
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [g,r,b,a,p,l]=await Promise.all([request<Gift[]>('/api/v1/rewards/gifts/'),allRedemptions(),api.myStarBalance(),request<Allowances>('/api/v1/rewards/allowances/'),grant?api.rewardAudience():Promise.resolve([]),api.leaderboard(period)]);setGifts(g);setRows(r);setBalance(b);setLimits(a);setPeople(p);setRanking(l)}catch(e){setError(e instanceof Error?e.message:'Không tải được phần thưởng.')}finally{setLoading(false)}},[grant,period])
 useEffect(()=>{void load()},[load])
 async function run(action:()=>Promise<unknown>,message:string){setBusy(true);setError('');setSuccess('');try{await action();setSuccess(message);await load()}catch(e){setError(e instanceof Error?e.message:'Không thực hiện được thao tác.')}finally{setBusy(false)}}
 const post=(url:string,data:unknown)=>request('/api/v1/rewards/'+url,{method:'POST',body:JSON.stringify(data)})
 const decide=(r:Redemption,action:string)=>run(()=>post(`redemptions/${r.uuid}/decision/`,{action,note:notes[r.uuid]??''}),'Đã cập nhật yêu cầu.')
 const tabs=[['gifts','Quà tặng'],['balance','Sao của tôi'],['requests','Yêu cầu đổi thưởng'],['ranking','Bảng xếp hạng'],...(grant?[['grant','Cấp sao']]:[]),...(manager?[['manage','Quản lý quà'],['quota','Hạn mức Team']]:[])]
 return <section className="rewards-store" aria-busy={busy||loading}>
  <header className="store-heading"><div><h2>Sao & Đổi thưởng</h2><p>Tích lũy từ đóng góp, chọn phần thưởng bạn yêu thích.</p></div><div className="store-balance"><span>Sao khả dụng<strong>{balance.balance}</strong></span><span>Đang giữ đổi quà<strong>{balance.held??0}</strong></span></div></header>
  <nav className="store-tabs" aria-label="Sao và Đổi thưởng">{tabs.map(([id,title])=><button key={id} disabled={busy} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}>{title}</button>)}</nav>
  {error&&<p className="alert alert--error" role="alert">{error}<button onClick={()=>void load()}>Tải lại</button></p>}{success&&<p role="status">{success}</p>}
  {loading?<p role="status">Đang tải phần thưởng…</p>:<>
  {tab==='gifts'&&<><label>Tìm quà<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tên hoặc nhóm quà"/></label>
   {selected&&<section className="store-confirm" aria-label="Xác nhận đổi quà"><h3>Đổi {selected.title}?</h3><p>Giữ {selected.cost} sao và một phần quà chờ HR/CEO duyệt. Hoàn sao nếu hủy hoặc bị từ chối trước khi trao.</p><button className="primary-button" disabled={busy} onClick={()=>void run(async()=>{await post('redemptions/',{gift_uuid:selected.uuid,expected_cost:selected.cost,request_key:key.current});setSelected(null);key.current=crypto.randomUUID()},'Đã gửi yêu cầu đổi quà.')}>Xác nhận đổi {selected.cost} sao</button><button className="secondary-button" disabled={busy} onClick={()=>setSelected(null)}>Quay lại</button></section>}
   <div className="gift-grid">{gifts.filter(g=>g.active&&`${g.title} ${g.category}`.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi'))).map(g=><article className="gift-item" key={g.uuid}><small>{g.category}</small><h3>{g.title}</h3><p>{g.description}</p><div><strong>{g.cost} sao</strong><span>Còn {g.stock}</span></div><button className="primary-button" disabled={busy||g.stock<1||balance.balance<g.cost} onClick={()=>{key.current=crypto.randomUUID();setSelected(g)}}>{g.stock<1?'Hết quà':balance.balance<g.cost?'Chưa đủ sao':'Đổi quà'}</button></article>)}</div>
   {!gifts.some(g=>g.active)&&<div className="store-empty"><h3>Danh mục quà đang được chuẩn bị</h3><p>HR thiết lập mức sao và số lượng trước khi mở đổi. Bạn vẫn có thể xem sao và lịch sử của mình.</p></div>}</>}
  {tab==='balance'&&<section><h3>Lịch sử sao của tôi</h3><p>Sao khả dụng đã trừ phần đang giữ cho yêu cầu đổi quà. Sao đã cấp không hết hạn.</p>{!balance.ledger.length&&<p>Chưa có giao dịch.</p>}{balance.ledger.map(e=><article className="store-ledger" key={e.uuid}><time>{new Date(e.created_at).toLocaleDateString('vi-VN')}</time><span><strong>{e.reason}</strong><small>{e.entry_type_label} · {e.actor_name}</small></span><b>{e.amount>0?'+':''}{e.amount}</b></article>)}</section>}
  {tab==='requests'&&<section><h3>{manager?'Duyệt và trao phần thưởng':'Yêu cầu của tôi'}</h3>{!rows.length&&<p>Chưa có yêu cầu đổi thưởng.</p>}{rows.map(r=><article className="redemption-item" key={r.uuid}><header><h4>{r.gift_title} · {r.cost} sao</h4><span>{r.status_label}</span></header><p>{manager?`${r.employee_name} · `:''}{new Date(r.created_at).toLocaleDateString('vi-VN')}</p>{r.note&&<p>Lý do: {r.note}</p>}{['pending','approved'].includes(r.status)&&<><label>Lý do hủy / từ chối<input maxLength={500} value={notes[r.uuid]??''} onChange={e=>setNotes({...notes,[r.uuid]:e.target.value})}/></label><div className="store-actions">{manager&&r.employee!==session.employee_uuid&&r.status==='pending'&&<><button className="primary-button" disabled={busy} onClick={()=>void decide(r,'approve')}>Duyệt yêu cầu</button><button className="secondary-button" disabled={busy||!notes[r.uuid]?.trim()} onClick={()=>void decide(r,'reject')}>Từ chối & hoàn sao</button></>}{manager&&r.employee!==session.employee_uuid&&r.status==='approved'&&<button className="primary-button" disabled={busy} onClick={()=>void decide(r,'fulfill')}>Xác nhận đã trao quà</button>}<button className="secondary-button" disabled={busy||!notes[r.uuid]?.trim()} onClick={()=>void decide(r,'cancel')}>Hủy & hoàn sao</button></div></>}</article>)}</section>}
  {tab==='ranking'&&<section><h3>Bảng xếp hạng sao</h3><label>Kỳ<select value={period} onChange={e=>setPeriod(e.target.value as typeof period)}><option value="month">Tháng</option><option value="quarter">Quý</option><option value="year">Năm</option></select></label><p>Đổi quà không làm giảm thành tích trên bảng xếp hạng.</p>{ranking.map(r=><article className="store-ledger" key={r.employee_uuid}><strong>{r.rank}</strong><span>{r.display_name}<small>{r.team_name}</small></span><b>{r.stars} sao</b></article>)}</section>}
  {tab==='grant'&&<section><h3>Cấp sao cho nhân sự</h3><p>Leader dùng chung hạn mức Team trong tháng. Điều chỉnh giảm chỉ dành cho HR/CEO.</p><ul>{limits.allowances.filter(a=>a.month.startsWith(new Date().toLocaleDateString('sv-SE').slice(0,7))).map(a=><li key={a.team_uuid}>{a.team_name}: đã cấp {a.used}/{a.limit} sao</li>)}</ul><form className="store-form" onSubmit={e=>{e.preventDefault();void run(async()=>{await post('stars/grant/',{...star,idempotency_key:starKey.current});starKey.current=crypto.randomUUID();setStar({...star,reason:''})},'Đã ghi giao dịch sao.')}}><label>Nhân sự<select required value={star.employee_uuid} onChange={e=>setStar({...star,employee_uuid:e.target.value})}><option value="">Chọn nhân sự</option>{people.map(p=><option key={p.uuid} value={p.uuid}>{p.display_name} · {p.team_name}</option>)}</select></label><label>Số sao<input type="number" required min={manager?-1000000:1} max={1000000} value={star.amount} onChange={e=>setStar({...star,amount:Number(e.target.value)})}/></label><label>Lý do<input required maxLength={500} value={star.reason} onChange={e=>setStar({...star,reason:e.target.value})}/></label><button className="primary-button" disabled={busy||star.amount===0}>Cấp / điều chỉnh sao</button></form></section>}
  {tab==='manage'&&<section><h3>{edit?'Chỉnh sửa quà':'Thêm quà vào danh mục'}</h3><p>Mức sao và số lượng do HR thiết lập. Quà chỉ hiển thị khi bật “Mở đổi”.</p><label>Gợi ý quà<select value="" onChange={e=>setForm({...form,title:e.target.value})}><option value="">Chọn gợi ý hoặc tự nhập</option>{suggestions.map(x=><option key={x}>{x}</option>)}</select></label><form className="store-form" onSubmit={e=>{e.preventDefault();void run(async()=>{await request(`/api/v1/rewards/gifts/${edit?`${edit}/`:''}`,{method:edit?'PATCH':'POST',body:JSON.stringify(form)});setForm(blank);setEdit('')},'Đã lưu quà.')}}><label>Tên quà<input required maxLength={180} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Nhóm quà<input required maxLength={80} value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Mô tả / điều kiện nhận<textarea maxLength={3000} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Số sao để đổi<input required type="number" min={1} max={1000000} value={form.cost} onChange={e=>setForm({...form,cost:Number(e.target.value)})}/></label><label>Số lượng còn có thể đổi<input required type="number" min={0} max={1000000} value={form.stock} onChange={e=>setForm({...form,stock:Number(e.target.value)})}/></label><label className="store-check"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Mở đổi</label><button className="primary-button" disabled={busy}>Lưu quà</button>{edit&&<button type="button" onClick={()=>{setEdit('');setForm(blank)}}>Hủy chỉnh sửa</button>}</form><h3>Danh mục quản lý</h3>{gifts.map(g=><article className="store-ledger" key={g.uuid}><span><strong>{g.title}</strong><small>{g.cost} sao · Còn {g.stock} · {g.active?'Đang mở':'Đang ẩn'}</small></span><button className="secondary-button" disabled={busy} onClick={()=>{setEdit(g.uuid);setForm(g)}}>Sửa quà</button></article>)}</section>}
  {tab==='quota'&&<section><h3>Hạn mức cấp sao theo Team</h3><p>Chưa đặt hạn mức thì Leader chưa cấp được sao. Hạn mức tính theo tháng và dùng chung cho các Leader của Team.</p><form className="store-form" onSubmit={e=>{e.preventDefault();void run(()=>post('allowances/',{...quota,month:quota.month+'-01'}),'Đã lưu hạn mức.')}}><label>Team<select required value={quota.team_uuid} onChange={e=>setQuota({...quota,team_uuid:e.target.value})}><option value="">Chọn Team</option>{limits.teams.map(t=><option key={t.uuid} value={t.uuid}>{t.name}</option>)}</select></label><label>Tháng<input required type="month" value={quota.month} onChange={e=>setQuota({...quota,month:e.target.value})}/></label><label>Hạn mức sao<input required type="number" min={0} max={1000000} value={quota.limit} onChange={e=>setQuota({...quota,limit:Number(e.target.value)})}/></label><button className="primary-button" disabled={busy}>Lưu hạn mức</button></form>{limits.allowances.map(a=><p key={a.team_uuid+a.month}>{a.team_name} · {a.month.slice(0,7)} · {a.used}/{a.limit} sao đã cấp</p>)}</section>}
  </>}
 </section>
}
