# Generated by Django 5.2.17 on 2026-10-02 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_domain', '0006_add_assetcontrol_product_entitlement'),
        ('rewards_domain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='starledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('grant', 'Cấp sao'), ('adjustment', 'Điều chỉnh'), ('hold', 'Giữ sao đổi quà'), ('refund', 'Hoàn sao đổi quà')], max_length=16),
        ),
        migrations.CreateModel(
            name='RewardGift',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=80)),
                ('cost', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['cost', 'title'],
                'constraints': [models.CheckConstraint(condition=models.Q(('cost__gt', 0)), name='gift_positive_cost')],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gift_title', models.CharField(max_length=180)),
                ('cost', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('fulfilled', 'Đã trao quà'), ('rejected', 'Từ chối'), ('cancelled', 'Đã hủy')], default='pending', max_length=16)),
                ('request_key', models.UUIDField(unique=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people_domain.employee')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rewards_domain.rewardgift')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamStarAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('limit', models.PositiveIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people_domain.team')),
            ],
        ),
        migrations.AddField(
            model_name='starledgerentry',
            name='allowance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rewards_domain.teamstarallowance'),
        ),
        migrations.AddConstraint(
            model_name='teamstarallowance',
            constraint=models.UniqueConstraint(fields=('team', 'month'), name='unique_team_star_month'),
        ),
    ]
